# Generated by Django 5.0.6 on 2025-10-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('loan_start_date', models.DateField()),
                ('number_of_payments', models.PositiveIntegerField()),
                ('periodicity_value', models.PositiveIntegerField(default=1)),
                ('periodicity_unit', models.CharField(choices=[('d', 'days'), ('w', 'weeks'), ('m', 'months')], max_length=1)),
                ('interest_rate', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('outstanding_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('outstanding_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('principal_fixed', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='schedule.loanschedule')),
            ],
            options={
                'ordering': ('seq',),
                'unique_together': {('schedule', 'seq')},
            },
        ),
    ]
